python baseline.py kitchen dvd
python baseline.py kitchen books
python baseline.py kitchen electronics
python baseline.py dvd kitchen
python baseline.py dvd books
python baseline.py dvd electronics
python baseline.py books kitchen
python baseline.py books dvd
python baseline.py books electronics
python baseline.py electronics kitchen
python baseline.py electronics dvd
python baseline.py electronics books
